using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace StreamServices.Services
{
    /// <summary>
    /// EventArg to be used whenever firing events from a IStreamConsumer class
    /// </summary>
    public class StreamDataEventArgs : EventArgs
    {
        /// <summary>
        /// The last EventData generated by the service provider
        /// </summary>
        public EventData EventData { get; set; }

        /// <summary>
        /// All Buffered data
        /// </summary>
        public List<EventData> BufferedValues { get; set; }

        /// <summary>
        /// Default event constructor
        /// </summary>
        /// <param name="data">The last EventData</param>
        /// <param name="bufferedValues">A snapshot of the buffer</param>
        public StreamDataEventArgs(EventData data, List<EventData> bufferedValues)
        {
            EventData = data;
            BufferedValues = bufferedValues;
        }
    }
}
